# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4f1f70a59f1f0d2ec362cff4bd2d447593187f08c6405b0317bb0cefa5b27e5c1bd8e71276a8483f421860447b8392ffdc3678df0e37d84b61760c745fe41a56

test:
  secret_key_base: 3ab91f705cf2b99ab1752a28a69a434848c7eab3eecfb574d5e3759569dd1760130b29fa105a4a2fca4d16a9cfdf5ca118a3188faf2509afac4fcd4c3f577429

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
